SwWb/config/routes.rb
### Changed WebApp to SwWb
WebApp::Application.routes.draw do

    get "/" => redirect("/home")
    get  "/home"         => "swwb#home",         :as => "home"
    get  "/resources"    => "swwb#resources",    :as => "resources"
    get  "/about"        => "swwb#about",        :as => "about"
    get  "/contact"      => "swwb#contact",      :as => "contact"
    post "/contact_send" => "swwb#contact_send", :as => "contact_send"
    get  "/login"        => "users#login",       :as => "login"
    post "/login"        => "users#login",       :as => "login"
    get  "/login_guest"  => "users#login_guest", :as => "login_guest"
    get  "/logout"       => "users#logout",      :as => "logout"

    resources :songs, :verses

    resources :titles, :only  => [:index, :create, :new, :edit, :update]
    get  "/titles/:id/delete" => "titles#delete", :as => "delete"

    ### Example:
    ###   resources :songs, :only => [:index, :create, :new, :edit, :show,
    ###                               :update, :destroy]

end

SwWb/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible(:username)
  attr_accessible(:password_digest)

  validates_presence_of :username
  validates_presence_of :password

### Add validates_uniqueness_of :username, "message" => "<msg>"

  has_secure_password

  has_many :songs
  has_many :titles
  has_many :verses
end

SwWb/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def login
      @page_title = "Sign In"

      unless params["username"]
        render:login
        return
      end

      username = params["username"]
      password = params["password"]
      named_user = User.where({ :username => username }).first

      if named_user
        if named_user.authenticate(password)
          flash[:success]           = "Welcome #{username}, you have signed in!"
          session[:logged_in_user_id]= named_user.id
          redirect_to home_path
        else
          flash[:error] = "Invalid password, please try again"
          render :login
        end
      else
        flash[:error] = "Username not found, please try again"
        render :login
      end
    end

    def login_guest
      username = "guest"
      named_user = User.where({ :username => username }).first
      if named_user
        session[:logged_in_user_id] = named_user.id
        flash[:success]             = "Welcome #{username}, you have signed in!"
        redirect_to home_path
      else
        flash[:error] = "Username not found, please try again"
        render :login        
      end
    end

    def logout
###binding.pry
      reset_session
      @logged_in_user = nil
      flash[:success] = "You have successfully signed out!"
      redirect_to home_path
    end

end

SwWb/app/views/users/login.erb
    <div class="whole-page">

      <div class="logo-and-title">
        <div class="logo">
          <img src="/images/logo.jpg" alt="Logo" width="135" height="65"
               border="2" />
        </div>
        <br/>
        <div class="title">
          <img src="/images/banner.jpg" alt="Banner" width="585"
               height="158" border="2" />
          <h1>SongWriting WorkBench (SWWB)</h1>
        </div>
      </div>

      <div class="content">
        <h2><%= @page_title %></h2>

        <form method="post" action="<%= login_path %>">
          <br/>
          <div class="login-heading">Username: </div>
          <input type="text" name="username" value="<%= params["username"] %>"/>
          <br/>
          <div class="login-heading">Password: </div>
          <input type="password" name="password" value=""/>
          <br/><br/>
          <button style="margin-left:75px;">Sign In</button>
          &emsp;&emsp;<%= link_to "Sign In as guest", login_guest_path %>
          <br/><br/><br/><br/>
        </form>

        <div style="margin-left:75px;">
          <%= link_to "Return to home page", home_path %>
        </div>
        <br/><br/><br/>
      </div>

<%= render :partial => "layouts/footer" %>