SwWb/config/routes.rb
### Changed WebApp to SwWb
WebApp::Application.routes.draw do

    get "/" => redirect("/home")
    get  "/home"         => "swwb#home",         :as => "home"
    get  "/resources"    => "swwb#resources",    :as => "resources"
    get  "/about"        => "swwb#about",        :as => "about"
    get  "/contact"      => "swwb#contact",      :as => "contact"
    post "/contact_send" => "swwb#contact_send", :as => "contact_send"
    get  "/login"        => "users#login",       :as => "login"
    post "/login"        => "users#login",       :as => "login"
    get  "/login_guest"  => "users#login_guest", :as => "login_guest"
    get  "/logout"       => "users#logout",      :as => "logout"

    resources :songs, :verses

    resources :titles, :only  => [:index, :create, :new, :edit, :update]
    get  "/titles/:id/delete" => "titles#delete", :as => "delete"

    ### Example:
    ###   resources :songs, :only => [:index, :create, :new, :edit, :show,
    ###                               :update, :destroy]

end

SwWb/app/views/layouts/_errors.erb
<!-- Begin _errors.erb --> 
<% if object.errors.size > 0 %>
  <div class="errors">
    Error(s):
    <ul>
    <% for error in object.errors.full_messages %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- End _errors.erb --> 

SwWb/app/views/layouts/_footer.erb
<!-- Begin _footer.erb -->
      <br/>
      <hr>
      <div class="footer-logo-and-detail">
        <div class="footer-logo">
          <img src="/images/ladybug.jpg" alt="Footer Logo"
               width="50" height="50" border="1">
        </div>
        <div class="footer-detail">
          <br/>
          &copy; <i>2013 SongWriting WorkBench</i>
        </div>
      </div>

    </div>
<!-- End _footer.erb -->

SwWb/app/views/layouts/_header.erb
<!-- Begin _header.erb -->
    <div class="whole-page">

      <div class="logo-and-title">
        <div class="logo">
          <img src="/images/logo.jpg" alt="Logo" width="96" height="47"
               border="2" />
        </div>
        <br/>
        <div class="title">
          <img src="/images/banner.jpg" alt="Banner" width="585"
               height="158" border="2" />
          <h1>SongWriting WorkBench (SWWB)</h1>
        </div>
        <div class="user-sign-in-out">
          <% unless @logged_in_user %>
            &emsp;&emsp;<a href="/login">Sign In</a>
          <% else %>
              &emsp;&emsp;<%= @logged_in_user.username + " - " %>
              <a href="/logout">Sign Out</a>
          <% end %>
        </div>
      </div>

      <hr align='center' width='75%'>
      <div class='main-nav-bar'>
        <table class='main-table'>
          <tr class='main-td'>
            <td> <%= link_to("HOME", home_path) %> </td>
            <td> <%= link_to("RESOURCES", resources_path) %> </td>
            <td> <%= link_to("ABOUT SWWB", about_path) %> </td>
            <td> <%= link_to("CONTACT SWWB", contact_path) %> </td>
          </tr>
        </table>
      </div>
      <hr align='center' width='75%'>
<!-- End  _header.erb -->

SwWb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SongWriting WorkBench</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>

  <%# ### Added flash display %>
  <% for flash_type in [:error, :success] %>
    <% if flash[flash_type] %>
      <div class="flash flash-<%= flash_type %>">
        <%= flash[flash_type] %>
      </div>
    <% end %>
  <% end %>

<%= yield %>

  </body>
</html>