SwWb/config/routes.rb
### Changed WebApp to SwWb
WebApp::Application.routes.draw do

    get "/" => redirect("/home")
    get  "/home"         => "swwb#home",         :as => "home"
    get  "/resources"    => "swwb#resources",    :as => "resources"
    get  "/about"        => "swwb#about",        :as => "about"
    get  "/contact"      => "swwb#contact",      :as => "contact"
    post "/contact_send" => "swwb#contact_send", :as => "contact_send"
    get  "/login"        => "users#login",       :as => "login"
    post "/login"        => "users#login",       :as => "login"
    get  "/login_guest"  => "users#login_guest", :as => "login_guest"
    get  "/logout"       => "users#logout",      :as => "logout"

    resources :songs, :verses

    resources :titles, :only  => [:index, :create, :new, :edit, :update]
    get  "/titles/:id/delete" => "titles#delete", :as => "delete"

    ### Example:
    ###   resources :songs, :only => [:index, :create, :new, :edit, :show,
    ###                               :update, :destroy]

end

SwWb/app/controllers/verses_controller.rb
class VersesController < ApplicationController

    before_filter(:except => ["index", "show"]) {
      unless @logged_in_user
        flash[:error] = "You must sign in to create and alter verses"
        redirect_to("/login") 
        return
      end
    }

    ### Note: Using a private method to be called by create and update may
    ###   be better, but there may be issues with using "return" in the method
    ### Note: Instead of a before_filter, I can do the actual check in the
    ###   action below and it would require a return statement after
    ###   the redirect_to()
    before_filter(:only => ["create", "update"]) {
###binding.pry
      unless params[:cancel].blank?
        flash[:success] = "Your action has been cancelled"
        redirect_to("/home") 
      end
    }

    def index
      @page_title = "List Verses"
      if @logged_in_user
        @verses = @logged_in_user.verses.order("created_at")
      else
        # @verses = Verse.order("created_at")
        admin_user = User.where({ :username => "admin1357" }).first
        @verses    = admin_user.verses.order("created_at")
      end
      render :index
    end
 
    def create
      @page_title = "Add Song Verse"
 
      @verse         = Verse.new
      @verse.date    = Date.today
      @verse.tag     = params["verse-tag"]
      @verse.content = params["verse-content"]
      @verse.user_id = session[:logged_in_user_id]

      if @verse.save
        flash[:success] = "Your verse has been created"
        redirect_to("/home") 
      else
        flash[:error] = "Your verse could not be created"
        render :new
      end
    end

    def new
      @page_title = "Add Song Verse"
      @verse      = Verse.new
      render :new
    end

    def edit
      @page_title = "Edit Verse"

      verse_id = params["id"]
      @verse   = @logged_in_user.verses.find(verse_id)
      render :edit
    end

    def show
      @page_title = "Show Verse"

      verse_id = params["id"]
      @verse   = Verse.where({ :id => verse_id }).first
      render :show
    end

    def update
      @page_title = "Edit Verse"

      verse_id       = params["id"]
      @verse         = @logged_in_user.verses.find(verse_id)

      @verse.tag     = params["verse-tag"]
      @verse.content = params["verse-content"]
      @verse.user_id = session[:logged_in_user_id]

      if @verse.save
        flash[:success] = "Your verse has been updated"
        redirect_to("/home") 
      else
        flash[:error] = "Your verse could not be updated"
        render :edit
      end
    end

    def destroy
      verse_id = params["id"]
      @verse   = @logged_in_user.verses.find(verse_id)

      @verse.destroy
      flash[:success] = "Your verse has been deleted"
      redirect_to("/home")
    end

end

SwWb/app/views/verses/edit.erb
<%= render :partial => "layouts/errors", :locals => { :object => @verse } %>

<%= render :partial => "layouts/header" %>

      <div class='content'>

        <h2><%= @page_title %></h2>

        <form method="POST" action="/verses/<%= @verse.id %>">
          <input name="_method" type="hidden" value="PUT">

          <br/>
          <div class="text-field">
            <div class="text-field-block">Verse Tag:</div>
            <input type="text" class="textbox-style" style="margin-right:165px;"
                   name="verse-tag" placeholder="Not Required"
                   value="<%= @verse.tag %>" size="50" maxlength="75"/>
            Characters used: <i><%= @verse.content.length %></i>/750
          </div>

          <div class="text-field">
            <div class="textarea-field-block">Verse Content:</div>
            <textarea class="textarea-style" name="verse-content"
                      placeholder="Required" rows='20' cols='80'
                      maxlength='750'><%= @verse.content %></textarea>
          </div>

          <br/>
          <div class="add-edit-verse-submit-field">
            <input type="submit" name="edit" value="Edit Complete">
          </div>
          <input type="submit" name="cancel" value="Cancel">

        </form>

      </div>

<%= render :partial => "layouts/footer" %>

SwWb/app/views/verses/index.erb
<%= render :partial => "layouts/header" %>

      <div class='content'>

        <h2><%= @page_title %></h2>

        &raquo;
          Select content of verse to view, &nbsp;verses ordered by date created.
        <br/><br/><br/>

        <div class="list-verse">
          <% if @verses.empty? %>
            No verses exist
          <% end %>

          <% for verse in @verses %>
            <div class="list-verse-label">Tag:</div>
            <% if verse.tag.to_s == "" %>
              No tag for this verse
            <% else %> 
              <i><%= verse.tag %></i>
            <% end %>
            <br/>

            <div class="list-verse-label">Date:</div>
              <%= verse.date.strftime("%B %-d, %Y - %A") %> <br/>

            <% if verse.content.to_s == "" %>
            <%   content= "No content for this verse" %>
            <% elsif verse.content.length > 30 %>
            <%   content= simple_format "  " + h(verse.content[0,30]) + "..." %>
            <% else %>
            <%   content = simple_format h(verse.content) %>
            <% end %>

            <div class="list-verse-label">Content: </div>
              <i><%= link_to(content, verse_path(verse)) %></i><br/>
          <% end %>
          <br/>
        </div>

      </div>

<%= render :partial => "layouts/footer" %>

SwWb/app/views/verses/new.erb
<%= render :partial => "layouts/errors", :locals => { :object => @verse } %>

<%= render :partial => "layouts/header" %>

      <div class='content'>

        <h2><%= @page_title %></h2>

        <form method="POST" action="/verses">
          <br/>
          <div class="text-field">
            <div class="text-field-block">Verse Tag:</div>
            <input type="text" class="textbox-style" style="margin-right:160px;"
                   name="verse-tag" placeholder="Not Required"
                   value="<%= @verse.tag%>" size="50" maxlength="75"/>
            Maximum characters: 750
            <br/>
            <div class="textarea-field-block">Verse Content:</div>
            <textarea class="textarea-style" name="verse-content"
                      placeholder="Required" rows='20' cols='80'
                      maxlength='750'><%= @verse.content %></textarea>
          </div>

          <br/>
          <div class="add-edit-verse-submit-field">
            <input type="submit" name="create" value ="Create Verse">
          </div>
          <input type="submit" name="cancel" value="Cancel">

        </form>

      </div>

<%= render :partial => "layouts/footer" %>

SwWb/app/views/verses/show.erb
<%= render :partial => "layouts/header" %>

      <div class='content'>

        <h2><%= @page_title %></h2>

        <div class="list-verse">

          <div class="list-verse-label">Tag:</div>
          <% if @verse.tag.to_s == "" %>
            No tag for this verse
          <% else %> 
            <i><%= @verse.tag %></i>
          <% end %>
          <br/>

          <div class="list-verse-label">Date:</div>
            <%= @verse.date.strftime("%B %-d, %Y - %A") %> <br/>

          <div class="list-verse-label"
               style="margin-right:435px;">Content:</div>
          Characters used: <i><%= @verse.content.length %></i>/750

          <textarea class="textarea-style" placeholder="Required"
                rows='20' cols='80' readonly><%= h(@verse.content) %></textarea>

          <br/><br/>
        </div>

        <% if @logged_in_user %>
          <%# ### form-method-action-get with named route %>
          <form method="GET" action="<%= edit_verse_path(@verse) %>">
            <div class="show-verse-submit-field">
               <input type="submit" value ="Edit Verse">
            </div>
          </form>

          <form method="POST" action="/verses/<%= @verse.id %>">
            <input name="_method" type="hidden" value="DELETE">
              <input type="submit" name="delete" value ="Delete Verse">
          </form>
        <% end %>

        <br/><div style="margin-left:275px;">
          <%= link_to "Return to List Verses", verses_path %>
        </div>

      </div>

<%= render :partial => "layouts/footer" %>