SwWb/config/routes.rb
### Changed WebApp to SwWb
WebApp::Application.routes.draw do

    get "/" => redirect("/home")
    get  "/home"         => "swwb#home",         :as => "home"
    get  "/resources"    => "swwb#resources",    :as => "resources"
    get  "/about"        => "swwb#about",        :as => "about"
    get  "/contact"      => "swwb#contact",      :as => "contact"
    post "/contact_send" => "swwb#contact_send", :as => "contact_send"
    get  "/login"        => "users#login",       :as => "login"
    post "/login"        => "users#login",       :as => "login"
    get  "/login_guest"  => "users#login_guest", :as => "login_guest"
    get  "/logout"       => "users#logout",      :as => "logout"

    resources :songs, :verses

    resources :titles, :only  => [:index, :create, :new, :edit, :update]
    get  "/titles/:id/delete" => "titles#delete", :as => "delete"

    ### Example:
    ###   resources :songs, :only => [:index, :create, :new, :edit, :show,
    ###                               :update, :destroy]

end

SwWb/app/controllers/swwb_controller.rb
class SwwbController < ApplicationController

    ### See ./application_controller.rb for before_filter to retrieve
    ###   @logged_in_user

    def home
      # Get the priority songs for this user, default are the admin songs
      if @logged_in_user
        priority_songs =
          @logged_in_user.songs.where({ :priority => [1,2,3,4] }).sort_by \
            { |song| song.priority }
      else
        admin_user = User.where({ :username => "admin1357" }).first
        priority_songs =
          admin_user.songs.where({ :priority => [1,2,3,4] }).sort_by \
            { |song| song.priority }
      end

      @song1 = priority_songs[0]
      @song2 = priority_songs[1]
      @song3 = priority_songs[2]
      @song4 = priority_songs[3]

      render :action => "home"
    end

    def resources
      @page_title = "Resources"
      render :action => "resources"
    end

    def about
      @page_title = "About SWWB"
      render :action => "about"
    end

    def contact
      @page_title   = "Contact SWWB"
      @errors       = []
      render :action => "contact"
    end

    def contact_send
      if params["cancel"].present?
        flash[:success] = "Your action has been cancelled"
        redirect_to("/home")
        return
      end

      @page_title   = "Contact SWWB"
      @errors       = []
      @name         = params["name"]
      @email        = params["email"]
      @phone        = params["phone"]
      @message      = params["message"]

      ### Using attr_accessor w/ validations for these fields might work instead
      if @name.empty?
        @errors += ["Your name is a required field"]
      end
      if @email.empty?
        @errors += ["Your email is a required field"]
      end
      if @message.empty?
        @errors += ["Your message is a required field"]
      end

      if @errors.size == 0
        subject  = ""
        subject +=
          "Message from SWWB - #{Date.today.strftime("%B %-d, %Y - %A")}"
        body  = ""
        body += "From:       #{@name}\n"
        body += "Email:      #{@email}\n"
        body += "Phone:      #{@phone}\n\n"
        body += "Message:\n\n#{@message}"

        ### Todo: Add exception handling for the case of a failure
        Pony.mail({
          :to      => "#{Pony.options[:via_options][:user_name]}",
          :subject => "#{subject}",
          :body    => "#{body}",
        })

        flash[:success] = "Your message has been sent!"
        redirect_to("/home")
      else
        flash[:error] = "Your form is incomplete"
        render :action => "contact"
      end
    end

end

SwWb/app/views/swwb/_make_song_current.erb
<!-- Begin _make_song_current.erb -->
  <form method="POST" action="/songs/<%= song.id %>">
    <input name="_method" type="hidden" value="PUT">

    <div class="list-title-label">
      <% if song.title.to_s == "" %>
        Title: No title for this song
      <% else %>
        Title: <i><%= song.title %></i>
      <% end %>
    </div>
    <input type="submit" name="make-current" value ="Set as Current Song">
    <br/>
  </form>
<!-- End _make_song_current.erb -->

SwWb/app/views/swwb/about.erb
<%= render :partial => "layouts/header" %>

      <div class='content'>
        <h2><%= @page_title %></h2>
        <p style="text-align:justify; margin-left:90px; margin-right:185px;">
        SongWriting WorkBench is a set of tools that can be used to assist in
        writing lyrics. This workbench will display the current song
        being worked on and allow editing of that song if you are logged in.
        SWWB will also allow new songs to be added. In addition, recently
        viewed songs will be displayed and each can be selected to become the
        current song. Finally, a list of assorted verse phrases and song titles
        can be maintained separately.
        <br/><br/>
        If you are not logged in, then you may view the default set of songs.
        The 'Set as Current Song' is also enabled. You may log in as 'guest'
        in order to create and alter your own songs, verses, and titles.
        </p>
        <br/><br/><br/><br/>
      </div>

<%= render :partial => "layouts/footer" %>

SwWb/app/views/swwb/contact.erb
      <%# My customized handling of required fields not populated %>
      <% if @errors.size > 0 %>
        <div class="errors">
          Error(s):
          <ul>
          <% for error in @errors %>
            <li><%= error %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

<%= render :partial => "layouts/header" %>

      <div class='content'>

        <h2><%= @page_title %></h2>

        <form method="POST" action="/contact_send">
          <font color="red">*</font>&nbsp;&nbsp;Required
          <br/><br/>
          <div class="text-field">
            <div class="text-field-block">Your Name:</div>
            <input type="text" class="textbox-style" name="name"
                   value="<%= @name %>" size="30" maxlength="30"/>
            <font color="red">*</font>
            <br/>

            <div class="text-field-block">Your Email:</div>
            <input type="text" class="textbox-style" name="email"
                   value="<%= @email %>" size="30" maxlength="30"/>
            <font color="red">*</font>
            <br/>

            <div class="text-field-block">Your Phone:</div>
            <input type="text" class="textbox-style" name="phone"
                   value="<%= @phone %>" size="30" maxlength="30"/>
            <br/><br/>

            <div class="textarea-field-block">Your Message:</div>
            <textarea name="message" class="textarea-style"
                      rows='10' cols='45'><%= @message %></textarea>
            <font color="red" style="position:absolute;">*</font>
          </div>

          <br/>
          <div class="contact-submit-field">
            <input type="submit" name="send" value ="Send Message">
          </div>
          <input type="submit" name="cancel" value="Cancel">
        </form>

      </div>

<%= render :partial => "layouts/footer" %>

SwWb/app/views/swwb/home.erb
<%= render({ :partial => "layouts/header" }) %>

      <script>
        function autoGenerate()
        {
          alert("Auto generate a hit song\n\n\
Not implemented - But if it was...\n\n\
I envision the capability of generating hit songs, with a catch - \
you would have to accept the disclaimer provided \
which may change your life forever!\n\n\
Like episodes from the Twilight Zone, being granted what you desire \
comes with a price.\n\n\
And, developing this feature would surely change me forever!\n")
        }
      </script>

      <div class='content'>

        <br/><br/>
        <div class="more-info" style="font-size:14px;">
          &raquo; Please see ABOUT SWWB for information about this site.
        </div>

        <br/><br/>
        <div class="current-song-heading-and-button">
          <div class="current-song-heading">

            <% if @song1 %>
              <% if @logged_in_user %>
                <form method="GET" action="<%= edit_song_path(@song1) %>">
                    <u>Current Song</u>
                    &nbsp; <button>Edit</button> <br/>
                </form>
              <% else %>
                <form method="GET" action="<%= song_path(@song1) %>">
                    <u>Current Song</u>
                    &nbsp; <button>Show</button> <br/>
                </form>
              <% end %>
            <% else %>
                <u>Current Song</u>
            <% end %>

            <%
              if @song1
               if @song1.content.length > 30
                 content = simple_format h(@song1.content[0,30]) + "..."
               else
                 content = simple_format h(@song1.content) end
             end
           %>

            <div class="current-song">
              <% if @song1.nil? %>
                No current song - try List Songs
              <% else %>
                <div class="list-song-label">Title:</div>
                <% if @song1.title.to_s == "" %>
                  No title for this song
                <% else %>
                  <i><%= @song1.title %></i>
                <% end %>

                <br/>
                <div class="list-song-label">Content:</div>
                  <i><%= content %></i> <br/>
              <% end %>
            </div>
          </div>
        </div>

        <div class="list-song-verse-links">
          <table class="list-song-verse-table">
            <tr class="list-song-verse-td">
              <td> <%= link_to "Add Song", new_song_path %>
              <td> <%= link_to "List Songs", songs_path %>
              <td> <%= link_to "Song Titles", titles_path %>
              <td style="line-height:60px;" colspan=2>&nbsp;</td>
            </tr>
            <tr class="list-song-verse-td">
              <td> <a href="/verses/new">Add Verse</a> </td>
              <td> <a href="/verses">List Verses</a> </td>
            </tr>
          </table>
        </div>

        <br/><br/>
        <div class="recent-songs-heading-and-links">

          <div class="recent-songs-heading">
            <u>Recently Modified Songs</u>
          </div>
            <input type="button" style="color:green; font-size:18px;"
                   onclick="autoGenerate()"
                   value="Auto Generate Song - Press Me" />

          <div class="recent-songs">
            <% if @song2.nil? %>
              No recent songs - try List Songs
            <% else %>
<%= render :partial => "make_song_current", :locals => { :song => @song2 } %>
              <% if @song3 %>
<%= render :partial => "make_song_current", :locals => { :song => @song3 } %>
                <% if @song4 %>
<%= render :partial => "make_song_current", :locals => { :song => @song4 } %>
                <% end %>
              <% end %>
            <% end %>
          </div>

        </div>
      </div>

<%= render({ :partial => "layouts/footer" }) %>

SwWb/app/views/swwb/resources.erb
<%= render :partial => "layouts/header" %>

      <div class='content'>
        <h2><%= @page_title %></h2>
        <br/><br/>
        <div class="link-thesaurus">
          <a href="http://thesaurus.com/" target="_blank">Thesaurus</a>
        </div>
        <br/><br/>
        <div class="link-rhyme-dict">
          <a href="http://www.rhymezone.com/"
             target="_blank">Rhyming Dictionary</a>
        </div>
        <br/><br/><br/><br/>
      </div>

<%= render :partial => "layouts/footer" %>